# workflow
# mainë¸Œëœì¹˜ì— ì»¤ë°‹ì‹œ í…ŒìŠ¤íŠ¸ë¥¼ ì‹¤í–‰í•œë‹¤.
name: Unit-Tests

on: # ì´ë²¤íŠ¸ ê°ì§€
  push:
    branch:
      - main #main ë¸Œëœì¹˜ì—ì„œ ì‹¤í–‰

jobs: # ì‘ì—…ë“¤
  Back-Unit-Tests:
    name: Unit tests
    runs-on: [ubuntu-latest] # ìš°ë¶„íˆ¬ ê°€ìƒí™˜ê²½
    steps:
      - name: Check out repo code
        uses: ./back/actions/checkout@v2
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Set up node
        uses: ./back/actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
          cache-dependency-path: |
            back/yarn.lock
      - name: Install dependencies
        run: |
          cd back
          yarn install
      - name: Run tests
        run: |
          cd back
          yarn test
      - name: If fail
        run: exit 1
        if: failure()
      - name: Job's status
        run: echo "ğŸŸ¢ This job's status is ${{ job.status }}"
